/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base_de_donnees;

import java.sql.*;
import aeroclub.Bdd;
import aeroclub.Parameters;
import aeroclub.ResultSetTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class MembreWindow extends javax.swing.JFrame {

    ResultSet rs;
    Bdd db;
    
    public MembreWindow() {
        db = new Bdd(new Parameters().HOST_DB, new Parameters().USERNAME_DB, 
             new Parameters().PASSWORD_DB, new Parameters().IPHOST, new Parameters().PORT);
        
        initComponents();
        table(); 
    }
    
    //fonction qui rempli la table
    public void table(){
        String a[] = {"num_membre","nom", "prenom", "adresse", "ville", "portable", "email"};
        rs = db.querySelect(a, "membres");
        table_membres.setModel(new ResultSetTableModel(rs));
    }
    
    public void actualiser(){
        recherche.setText("");
        num_membre.setText(""); 
        num_qualif.setText(""); 
        num_civilite.setText("");  
        nom.setText(""); 
        prenom.setText(""); 
        adresse.setText("");  
        code_postale.setText(""); 
        ville.setText("");  
        telephone.setText("");  
        portable.setText("");  
        email.setText("");  
        commentaire.setText("");  
        date_vm.setText("");  
        validite_vm.setText("");  
        date_sep.setText(""); 
        validite_sep.setText("");  
        num_badge.setText("");  
        profession.setText("");  
        date_naissance.setText("");  
        lieu_naissance.setText("");  
        carte_federale.setText(""); 
        date_attestation.setText("");  
        date_theo_bb.setText("");  
        date_theo_ppla.setText("");  
        numero_ppla.setText("");  
        date_ppla.setText("");
        date_bb.setText("");
        numero_bb.setText("");
        numero_ppla.setText("");
        date_entree.setText(""); 
        membre_actif.setSelected(false);  
        membre_inscrit.setSelected(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_membres = new javax.swing.JTable();
        deleteBtn = new javax.swing.JButton();
        deleteBtn1 = new javax.swing.JButton();
        deleteBtn3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        num_membre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        num_qualif = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        num_civilite = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        adresse = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        code_postale = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ville = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        telephone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        portable = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        commentaire = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        date_vm = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        validite_vm = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        date_sep = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        validite_sep = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        num_badge = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        profession = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        date_naissance = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        lieu_naissance = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        carte_federale = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        date_attestation = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        date_theo_bb = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        date_theo_ppla = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        numero_ppla = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        date_ppla = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        date_entree = new javax.swing.JTextField();
        membre_actif = new javax.swing.JCheckBox();
        membre_inscrit = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        date_bb = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        numero_bb = new javax.swing.JTextField();
        recherche = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        com_recherche = new javax.swing.JComboBox<String>();
        deleteBtn4 = new javax.swing.JButton();
        deleteBtn5 = new javax.swing.JButton();
        deleteBtn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Gestion des membres");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 30, 205, 28);

        jButton1.setText("retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 10, 71, 23);

        table_membres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "num_membre", "nom", "prenom", "adresse", "ville", "tel", "portable", "email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_membres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_membresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_membres);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 1140, 91);

        deleteBtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        deleteBtn.setText("supprimer");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn);
        deleteBtn.setBounds(200, 210, 129, 37);

        deleteBtn1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        deleteBtn1.setText("modifier");
        deleteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn1);
        deleteBtn1.setBounds(490, 210, 130, 37);

        deleteBtn3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        deleteBtn3.setText("rechercher");
        deleteBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn3);
        deleteBtn3.setBounds(710, 60, 135, 37);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("num_membre :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(21, 18, 109, 22);

        num_membre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_membreActionPerformed(evt);
            }
        });
        jPanel1.add(num_membre);
        num_membre.setBounds(140, 11, 130, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("num_qualif :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(21, 52, 90, 22);

        num_qualif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_qualifActionPerformed(evt);
            }
        });
        jPanel1.add(num_qualif);
        num_qualif.setBounds(140, 45, 130, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("num_civilité :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(21, 86, 96, 22);

        num_civilite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_civiliteActionPerformed(evt);
            }
        });
        jPanel1.add(num_civilite);
        num_civilite.setBounds(140, 79, 130, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("nom :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(21, 120, 41, 22);
        jPanel1.add(nom);
        nom.setBounds(140, 113, 130, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("prenom :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(21, 154, 64, 22);
        jPanel1.add(prenom);
        prenom.setBounds(140, 150, 130, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("adresse :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 190, 62, 22);
        jPanel1.add(adresse);
        adresse.setBounds(140, 190, 130, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("code postale :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 230, 98, 22);
        jPanel1.add(code_postale);
        code_postale.setBounds(140, 230, 130, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("ville :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 280, 38, 22);
        jPanel1.add(ville);
        ville.setBounds(140, 280, 130, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("telephone :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 330, 78, 22);
        jPanel1.add(telephone);
        telephone.setBounds(140, 330, 130, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("portable :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(287, 18, 67, 22);
        jPanel1.add(portable);
        portable.setBounds(410, 11, 130, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("email :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(287, 52, 47, 22);
        jPanel1.add(email);
        email.setBounds(410, 45, 130, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("commentaire :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(287, 86, 102, 22);
        jPanel1.add(commentaire);
        commentaire.setBounds(410, 79, 130, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("date_vm :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(290, 120, 71, 22);
        jPanel1.add(date_vm);
        date_vm.setBounds(410, 120, 130, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("validité_vm :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(290, 160, 92, 22);

        validite_vm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validite_vmActionPerformed(evt);
            }
        });
        jPanel1.add(validite_vm);
        validite_vm.setBounds(410, 160, 130, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("date_sep :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(290, 200, 72, 22);

        date_sep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_sepActionPerformed(evt);
            }
        });
        jPanel1.add(date_sep);
        date_sep.setBounds(410, 200, 130, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("validité_sep :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(290, 240, 93, 22);
        jPanel1.add(validite_sep);
        validite_sep.setBounds(410, 240, 130, 30);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("num_badge :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(290, 280, 92, 22);
        jPanel1.add(num_badge);
        num_badge.setBounds(410, 290, 130, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setText("profession :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(290, 330, 83, 22);
        jPanel1.add(profession);
        profession.setBounds(410, 330, 130, 30);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("date_naissance :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(560, 20, 116, 22);
        jPanel1.add(date_naissance);
        date_naissance.setBounds(750, 10, 130, 30);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setText("lieu_naissance :");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(560, 60, 111, 22);

        lieu_naissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lieu_naissanceActionPerformed(evt);
            }
        });
        jPanel1.add(lieu_naissance);
        lieu_naissance.setBounds(750, 50, 130, 30);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setText("carte_federale :");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(560, 100, 110, 22);
        jPanel1.add(carte_federale);
        carte_federale.setBounds(750, 90, 130, 30);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setText("date_attestation :");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(560, 130, 121, 22);
        jPanel1.add(date_attestation);
        date_attestation.setBounds(750, 130, 130, 30);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel25.setText("date_theorique_bb :");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(560, 170, 142, 22);
        jPanel1.add(date_theo_bb);
        date_theo_bb.setBounds(750, 170, 130, 30);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel26.setText("date_theorique_ppla :");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(560, 210, 154, 22);
        jPanel1.add(date_theo_ppla);
        date_theo_ppla.setBounds(750, 210, 130, 30);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel27.setText("numero_ppla :");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(900, 30, 110, 22);
        jPanel1.add(numero_ppla);
        numero_ppla.setBounds(1020, 20, 130, 30);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel28.setText("date_ppla :");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(560, 290, 78, 22);
        jPanel1.add(date_ppla);
        date_ppla.setBounds(750, 290, 130, 30);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel29.setText("date_entrée :");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(910, 70, 92, 20);
        jPanel1.add(date_entree);
        date_entree.setBounds(1020, 60, 130, 30);

        membre_actif.setText("membre_actif");
        jPanel1.add(membre_actif);
        membre_actif.setBounds(980, 120, 110, 23);

        membre_inscrit.setText("membre_inscrit");
        jPanel1.add(membre_inscrit);
        membre_inscrit.setBounds(980, 150, 110, 23);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel30.setText("date_bb :");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(560, 250, 66, 22);
        jPanel1.add(date_bb);
        date_bb.setBounds(750, 250, 130, 30);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel31.setText("numero_bb :");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(560, 330, 100, 22);
        jPanel1.add(numero_bb);
        numero_bb.setBounds(750, 330, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 260, 1200, 370);
        getContentPane().add(recherche);
        recherche.setBounds(860, 60, 300, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("rechercher par :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(720, 20, 120, 22);

        com_recherche.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "num_membre", "num_qualif", "num_civilite", "nom", "prenom", "adresse", "code_postal", "ville", "tel", "portable", "email", "commentaire", "date_vm", "validite_vm", "date_sep", "validite_sep", "num_badge", "profession", "date_naissance", "lieu_naissance", "carte_federale", "date_attestation", "date_theorique_bb", "date_theorique_ppla", "date_bb", "date_ppla", "numero_bb", "numero_ppla", "date_entree", "membre_actif", "membre_inscrit" }));
        getContentPane().add(com_recherche);
        com_recherche.setBounds(860, 20, 300, 30);

        deleteBtn4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        deleteBtn4.setText("actualiser");
        deleteBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn4);
        deleteBtn4.setBounds(780, 210, 130, 37);

        deleteBtn5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        deleteBtn5.setText("details");
        deleteBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn5);
        deleteBtn5.setBounds(650, 210, 99, 37);

        deleteBtn2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        deleteBtn2.setText("ajouter");
        deleteBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn2);
        deleteBtn2.setBounds(360, 210, 99, 37);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Principale p = new Principale();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        String numMembre = String.valueOf(table_membres.getValueAt(table_membres.getSelectedRow(), 0));
        if(JOptionPane.showConfirmDialog(this, "etes vous sûr de vouloir supprimer ce membre", "attention!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            db.queryDelete("membres", "num_membre="+ numMembre);
        }else{
            return;
        }
        table();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void deleteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn1ActionPerformed
        String membreActif = "0";
        String membreInscrit = "0";
        
        if(membre_actif.isSelected()){
            membreActif = "1";
        }
        
        if(membre_inscrit.isSelected()){
            membreInscrit = "1";
        }
        
        if(num_membre.getText().equals("") || num_qualif.getText().equals("") || num_civilite.getText().equals("")){
            JOptionPane.showMessageDialog(this, "num_membre, num_qualif et num_civilite doivent être remplis");
        }else{
            String[] colonne = {"num_membre", "num_qualif", "num_civilite", "nom", "prenom","adresse", "code_postal",
                                "ville", "tel", "portable", "email", "commentaire", "date_vm", "validite_vm", "date_sep",
                                "validite_sep", "num_badge", "profession", "date_naissance", "lieu_naissance", "carte_federale",
                                "date_attestation", "date_theorique_bb", "date_theorique_ppla", "date_bb", "date_ppla","numero_bb", 
                                "numero_ppla","date_entree", "membre_actif", "membre_inscrit"};
            
            String[] infos = {num_membre.getText(), num_qualif.getText(), num_civilite.getText(), nom.getText(), prenom.getText(),
                              adresse.getText(), code_postale.getText(), ville.getText(), telephone.getText(), portable.getText(),
                              email.getText(), commentaire.getText(), date_vm.getText(), validite_vm.getText(), date_sep.getText(),
                              validite_sep.getText(), num_badge.getText(), profession.getText(), date_naissance.getText(),
                              lieu_naissance.getText(), carte_federale.getText(), date_attestation.getText(), date_theo_bb.getText(),
                              date_theo_ppla.getText(), date_bb.getText(), date_ppla.getText(), numero_bb.getText(), numero_ppla.getText(),
                              date_entree.getText(), membreActif, membreInscrit};
            
            String id = String.valueOf(table_membres.getValueAt(table_membres.getSelectedRow(), 0));
            
            System.out.println(db.queryUpdate("membres", colonne, infos,"num_membre='"+ id +"'"));
            table();
            actualiser();
    }//GEN-LAST:event_deleteBtn1ActionPerformed
    }
    private void deleteBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn2ActionPerformed
        
        String membreActif = "0";
        String membreInscrit = "0";
        
        if(membre_actif.isSelected()){
            membreActif = "1";
        }
        
        if(membre_inscrit.isSelected()){
            membreInscrit = "1";
        }
        
        if(num_membre.getText().equals("") || num_qualif.getText().equals("") || num_civilite.getText().equals("")){
            JOptionPane.showMessageDialog(this, "num_membre, num_qualif et num_civilite doivent être remplis");
        }else{
            String[] colonne = {"num_membre", "num_qualif", "num_civilite", "nom", "prenom","adresse", "code_postal",
                                "ville", "tel", "portable", "email", "commentaire", "date_vm", "validite_vm", "date_sep",
                                "validite_sep", "num_badge", "profession", "date_naissance", "lieu_naissance", "carte_federale",
                                "date_attestation", "date_theorique_bb", "date_theorique_ppla", "date_bb", "date_ppla","numero_bb", 
                                "numero_ppla","date_entree", "membre_actif", "membre_inscrit"};
            
            String[] infos = {num_membre.getText(), num_qualif.getText(), num_civilite.getText(), nom.getText(), prenom.getText(),
                              adresse.getText(), code_postale.getText(), ville.getText(), telephone.getText(), portable.getText(),
                              email.getText(), commentaire.getText(), date_vm.getText(), validite_vm.getText(), date_sep.getText(),
                              validite_sep.getText(), num_badge.getText(), profession.getText(), date_naissance.getText(),
                              lieu_naissance.getText(), carte_federale.getText(), date_attestation.getText(), date_theo_bb.getText(),
                              date_theo_ppla.getText(), date_bb.getText(), date_ppla.getText(), numero_bb.getText(), numero_ppla.getText(),
                              date_entree.getText(), membreActif, membreInscrit};
            
            System.out.println(db.queryInsert("membres", colonne, infos));
            table();
            actualiser();
        }
    }//GEN-LAST:event_deleteBtn2ActionPerformed

    private void deleteBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn3ActionPerformed
        
        String a[] = {"num_membre","nom", "prenom", "adresse", "ville", "portable", "email"};
        
        if(recherche.getText().equals("") && !(com_recherche.getSelectedItem().equals("membre_actif") || com_recherche.getSelectedItem().equals("membre_inscrit"))){
            JOptionPane.showMessageDialog(this, "Vous devez entrer quelque chose");
        }else{
            if(com_recherche.getSelectedItem().equals("num_membre")){
                rs = db.fcSelectCommand(a, "membres", "num_membre LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("num_qualif")){
                rs = db.fcSelectCommand(a,"membres", "num_qualif LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("num_civilite")){
                rs = db.fcSelectCommand(a,"membres", "num_civilite LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("nom")){
                rs = db.fcSelectCommand(a,"membres", "nom LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("prenom")){
                rs = db.fcSelectCommand(a,"membres", "prenom LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("adresse")){
                rs = db.fcSelectCommand(a,"membres", "adresse LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("code_postal")){
                rs = db.fcSelectCommand(a,"membres", "code_postal LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("ville")){
                rs = db.fcSelectCommand(a,"membres", "ville LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("tel")){
                rs = db.fcSelectCommand(a,"membres", "tel LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("portable")){
                rs = db.fcSelectCommand(a,"membres", "portable LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("email")){
                rs = db.fcSelectCommand(a,"membres", "email LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("commentaire")){
                rs = db.fcSelectCommand(a,"membres", "commentaire LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("date_vm")){
                rs = db.fcSelectCommand(a,"membres", "date_vm LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("validite_vm")){
                rs = db.fcSelectCommand(a,"membres", "validite_vm LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("date_sep")){
                rs = db.fcSelectCommand(a,"membres", "date_sep LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("validite_sep")){
                rs = db.fcSelectCommand(a,"membres", "validite_sep LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("num_badge")){
                rs = db.fcSelectCommand(a,"membres", "num_badge LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("profession")){
                rs = db.fcSelectCommand(a,"membres", "profession LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("date_naissance")){
                rs = db.fcSelectCommand(a,"membres", "date_naissance LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("lieu_naissance")){
                rs = db.fcSelectCommand(a,"membres", "lieu_naissance LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("carte_federale")){
                rs = db.fcSelectCommand(a,"membres", "carte_federale LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("date_attestation")){
                rs = db.fcSelectCommand(a,"membres", "date_attestation LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("date_theorique_bb")){
                rs = db.fcSelectCommand(a,"membres", "date_theorique_bb LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("date_theorique_ppla")){
                rs = db.fcSelectCommand(a,"membres", "date_theorique_ppla LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("date_bb")){
                rs = db.fcSelectCommand(a,"membres", "date_bb LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("date_ppla")){
                rs = db.fcSelectCommand(a,"membres", "date_ppla LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("numero_bb")){
                rs = db.fcSelectCommand(a,"membres", "numero_bb LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("numero_ppla")){
                rs = db.fcSelectCommand(a,"membres", "numero_ppla LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("date_entree")){
                rs = db.fcSelectCommand(a,"membres", "date_entree LIKE '%"+ recherche.getText() +"%'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("membre_actif")){
                rs = db.fcSelectCommand(a,"membres", "membre_actif = '1'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }else if(com_recherche.getSelectedItem().equals("membre_inscrit")){
                rs = db.fcSelectCommand(a,"membres", "membre_inscrit = '1'");
                table_membres.setModel(new ResultSetTableModel(rs));
            }
        }
    }//GEN-LAST:event_deleteBtn3ActionPerformed

    private void num_membreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_membreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_membreActionPerformed

    private void num_qualifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_qualifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_qualifActionPerformed

    private void num_civiliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_civiliteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_civiliteActionPerformed

    private void validite_vmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validite_vmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validite_vmActionPerformed

    private void date_sepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_sepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_sepActionPerformed

    private void lieu_naissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lieu_naissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lieu_naissanceActionPerformed

    private void table_membresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_membresMouseClicked
        String id;
        id = (String.valueOf(table_membres.getValueAt(table_membres.getSelectedRow(), 0)));
        rs = db.querySelectAll("membres", "num_membre='"+ id +"'" );
        try {
            rs.next();
            num_membre.setText(rs.getString(1)); 
            num_qualif.setText(rs.getString(2)); 
            num_civilite.setText(rs.getString(3)); 
            nom.setText(rs.getString(4)); 
            prenom.setText(rs.getString(5)); 
            adresse.setText(rs.getString(6));   
            code_postale.setText(rs.getString(7)); 
            ville.setText(rs.getString(8)); 
            telephone.setText(rs.getString(9)); 
            portable.setText(rs.getString(10)); 
            email.setText(rs.getString(11)); 
            commentaire.setText(rs.getString(12)); 
            date_vm.setText(rs.getString(13)); 
            validite_vm.setText(rs.getString(14));  
            date_sep.setText(rs.getString(15)); 
            validite_sep.setText(rs.getString(16)); 
            num_badge.setText(rs.getString(17)); 
            profession.setText(rs.getString(18));  
            date_naissance.setText(rs.getString(19)); 
            lieu_naissance.setText(rs.getString(20)); 
            carte_federale.setText(rs.getString(21)); 
            date_attestation.setText(rs.getString(22));  
            date_theo_bb.setText(rs.getString(23)); 
            date_theo_ppla.setText(rs.getString(24)); 
            date_bb.setText(rs.getString(25));
            date_ppla.setText(rs.getString(26)); 
            numero_bb.setText(rs.getString(27));
            numero_ppla.setText(rs.getString(28)); 
            date_entree.setText(rs.getString(29)); 
        } catch (SQLException ex) {
            Logger.getLogger(MembreWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_table_membresMouseClicked

    private void deleteBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn4ActionPerformed
        table();
        actualiser();
    }//GEN-LAST:event_deleteBtn4ActionPerformed

    private void deleteBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn5ActionPerformed
        DetailsMembre details = null;
        try {
            details = new DetailsMembre(String.valueOf(table_membres.getValueAt(table_membres.getSelectedRow(),0)));
        } catch (SQLException ex) {
            System.out.println("le try a échoué !!!");
            Logger.getLogger(MembreWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        details.setVisible(true);
        this.dispose();       
    }//GEN-LAST:event_deleteBtn5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MembreWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MembreWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MembreWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MembreWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MembreWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresse;
    private javax.swing.JTextField carte_federale;
    private javax.swing.JTextField code_postale;
    private javax.swing.JComboBox<String> com_recherche;
    private javax.swing.JTextField commentaire;
    private javax.swing.JTextField date_attestation;
    private javax.swing.JTextField date_bb;
    private javax.swing.JTextField date_entree;
    private javax.swing.JTextField date_naissance;
    private javax.swing.JTextField date_ppla;
    private javax.swing.JTextField date_sep;
    private javax.swing.JTextField date_theo_bb;
    private javax.swing.JTextField date_theo_ppla;
    private javax.swing.JTextField date_vm;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteBtn1;
    private javax.swing.JButton deleteBtn2;
    private javax.swing.JButton deleteBtn3;
    private javax.swing.JButton deleteBtn4;
    private javax.swing.JButton deleteBtn5;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lieu_naissance;
    private javax.swing.JCheckBox membre_actif;
    private javax.swing.JCheckBox membre_inscrit;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField num_badge;
    private javax.swing.JTextField num_civilite;
    private javax.swing.JTextField num_membre;
    private javax.swing.JTextField num_qualif;
    private javax.swing.JTextField numero_bb;
    private javax.swing.JTextField numero_ppla;
    private javax.swing.JTextField portable;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField profession;
    private javax.swing.JTextField recherche;
    private javax.swing.JTable table_membres;
    private javax.swing.JTextField telephone;
    private javax.swing.JTextField validite_sep;
    private javax.swing.JTextField validite_vm;
    private javax.swing.JTextField ville;
    // End of variables declaration//GEN-END:variables
}
